title: "LUMT"
description: "A list of useful minecraft websites, tools, software, mods, ..."
markdown: kramdown

minima:
  skin: dark
  nav_pages:
    - a/index.md
    - lumt.md
    - contributors.md

exclude:
  - README.md
  - .github/
  - .vscode/
  - NOTES.md
  - CNAME
  - LICENSE
  - TODO.md

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

collections:
  a:
    output: true
