title: "List of useful Minecraft websites"
description: "A list of useful minecraft websites, tools, software, mods, ..."
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
markdown: kramdown

minima:
  skin: dark

exclude:
  - README.md
  - .github
  - NOTES.md
